import { Quicksand } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Shared/Header";
import Footer from "@/Components/Shared/Footer";
import Provider from "@/redux/Provider";

const quickSand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${quickSand.variable} antialiased`}
      >
        <Provider>
          <Header></Header>
          {children}
          <Footer></Footer>
        </Provider>
      </body>
    </html>
  );
}
